# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Basic"
license = "MIT"
licenselink = "https://github.com/r0xsh/hugo-theme-basic/blob/master/LICENSE"
description = "Basic blog theme styled with minimal tachyons"
homepage = "https://github.com/r0xsh/hugo-theme-basic"
tags = ["minimal", "tachyons", "blog", "responsive", "syntax highlighting", "google analytics", "plain", "clean", "starter", "rstats", "blogdown"]
features = ["blog", "blog series", "syntax highlighting", "google analytics", "tachyons"]
min_version = "0.60"

[author]
  name = "Antoine Bagnaud"
  homepage = "https://antoinebagnaud.me"


